name: build docker image
on:
  push:
    branches:
      - main
    # 只有这些路径的文件变更才会触发工作流
    paths:
      - 'src/**'
      - '.env'
      - 'requirements.txt'
      - 'run.py'
      - 'Dockerfile'

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

env:
  IMAGE_NAME: douban-showcase
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}        

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2 

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:latest